/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.etuxia.sign;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int myTransparent=0x7f040000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int logout=0x7f020001;
    }
    public static final class id {
        public static final int go=0x7f080001;
        public static final int logout=0x7f080003;
        public static final int url=0x7f080000;
        public static final int webview=0x7f080002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int webview=0x7f030001;
    }
    public static final class menu {
        public static final int menu=0x7f070000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int logout=0x7f050001;
    }
    public static final class style {
        public static final int Theme_Transparent=0x7f060000;
    }
}
